### ISSUE TITLE
try two image layers for transition screen

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/we-are-mini-golf-frontend#104]
https://scontent.frep1-1.fna.fbcdn.net/v/t1.15752-9/140210211_118639150122495_305438578291404759_n.png?_nc_cat=104&ccb=2&_nc_sid=ae9488&_nc_eui2=AeFebrDbNgULlOj7sKmKxiJZXUjeJ0_4JfVdSN4nT_gl9R9oNP2visrulw5Pp5Wuc8M&_nc_ohc=DBRUPOXe-m4AX9Ivd6n&_nc_ht=scontent.frep1-1.fna&oh=8d40440eb13abd34dc5a3584e6867b36&oe=602B81CD

https://scontent.frep1-1.fna.fbcdn.net/v/t1.15752-9/s1080x2048/140300394_766893627245120_187845481688338946_n.png?_nc_cat=101&ccb=2&_nc_sid=ae9488&_nc_eui2=AeHXDL6DOcTdAT3_BNHBEd6h6TyfmLztBInpPJ-YvO0EiYLj4SHIKj9MEeazLw5B1O0&_nc_ohc=_xEjdQW0nVkAX87Q0My&_nc_ht=scontent.frep1-1.fna&_nc_tp=30&oh=0d390d1803da045f0cb4776232ebe83a&oe=602C893A

these both should be centered on top of each other

**Comment by freedannyv** [comment]
@giteshk11 has been working on the flags and backgrounds, so it'd be better to let him finish it off.

**Comment by paulchrisluke** [comment]
He said assign to you last night
