### ISSUE TITLE
Number of players responsive adjustments

### ISSUE THREAD

**Issue by weareminigolf** [whynotearth/we-are-mini-golf-frontend#110]
Pull the logo and the name of the course a bit higher so it can fit the shapes.

![140552528_771239600409779_7700716664756576166_n](https://user-images.githubusercontent.com/76088063/105313853-4d13f700-5bbe-11eb-9423-db3a10c5f3ad.jpg)

**Comment by freedannyv** [comment]
@paulchrisluke and @weareminigolf , this might be another one of those background issues we faced with the new-hole screen. On iPhone X this is a perfect fit, but on bigger or smaller screens, the bg shrinks and grows moving things out of alignment. My suggestion would be to embed put the logo and text on the bg, rather than having them as separate elements. A couple of screenshots to show you why:

iPhoneX (375 x 812 px)
![image](https://user-images.githubusercontent.com/51437181/105437953-a189a600-5c94-11eb-9e0e-46de238da253.png)

wider than iPhoneX (512 x 812 px)
![image](https://user-images.githubusercontent.com/51437181/105438001-bbc38400-5c94-11eb-9e1a-5a2e308247be.png)

shorter than iPhoneX (375 x 622 px)
![image](https://user-images.githubusercontent.com/51437181/105438166-09d88780-5c95-11eb-8b7e-d6368093625e.png)

**Comment by paulchrisluke** [comment]
great suggestion @freedannyv , @weareminigolf are going to bake the logo in and provide asset

**Comment by weareminigolf** [comment]
meaning for every new course we would create a new image?
Sounds good to me, even I can do it. could you then create a place in the backend so we could upload the asset for new courses?

**Comment by freedannyv** [comment]
> meaning for every new course we would create a new image?
> Sounds good to me, even I can do it. could you then create a place in the backend so we could upload the asset for new courses?

@paulchrisluke

**Comment by paulchrisluke** [comment]
yea this exists, you uploaded images to it yea @freedannyv ?

**Comment by freedannyv** [comment]
> yea this exists, you uploaded images to it yea @freedannyv ?

@paulchrisluke , I don't think so. He wants a place to put the screen that comes immediately after the splash screen, course dependent. It would need to be in the course builder

**Comment by weareminigolf** [comment]
If we go with a custom image for all new course it is indeed easier if I can upload it in the back end otherwise if I need to ask you every time it won’t be convient for you guys...

**Comment by paulchrisluke** [comment]
ok I added a field on the backend for transitionScreenBackground for upload. It's deploying now, refresh staging backend to see in 10 minutes

**Comment by weareminigolf** [comment]
I don’t think @freedannyv was talking about the transition screen. For this issue I believe he uploaded the assets on Cloudinary and liked it to the transition screen so the right asset is chosen for the right PAR and Hole number.
It is for the page just after the landing page, with the logo, the name and the number of players selection. I thing the responsiveness of the page is too complicated to make it fit the background shapes so he suggested we actually upload one background per course with the logo and the name of the course directly on it

**Comment by paulchrisluke** [comment]
ok I've removed what I added and added an upload area for `playerSelectBackground` which we can use to dynamically change that screens background with the uploaded picture

**Comment by freedannyv** [comment]
I'd recommend updating the splash screen too (the first screen that we land on when an existing game isn't present), to bake the logo into that too. It would optimize the speed a little and prevent the screen loading before the logo (or visa versa) @weareminigolf @paulchrisluke

**Comment by weareminigolf** [comment]
Yes indeed, I asked Marine to do it already but I am not sure when she comes back, we’ll let you know

Sent from my iPhone

On 26 Jan 2021, at 08:53, Danny <notifications@github.com> wrote:

﻿

I'd recommend updating the splash screen too (the first screen that we land on when an existing game isn't present), to bake the logo into that too. It would optimize the speed a little and prevent the screen loading before the logo (or visa versa) @weareminigolf<https://github.com/weareminigolf> @paulchrisluke<https://github.com/paulchrisluke>

**Comment by freedannyv** [comment]
@weareminigolf I've updated the screens in the mean time to look like your design file. You can check in 5 minutes
