### ISSUE TITLE
speed optimizations

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/we-are-mini-golf-frontend#113]
- [ ] web optimize images and upload to strapi backend

https://router.vuejs.org/guide/advanced/data-fetching.html#fetching-after-navigation

https://www.npmjs.com/package/vue-router-prefetch

- [ ] show spinner on initial app load to give time for the first page to build

- [ ] show spinner before https://staging.app.weareminigolf.com/game-course
-consider loading the transition screen assets at this time as well

- [ ] show spinner after confirm score, before https://staging.app.weareminigolf.com/current-total

- [ ] show spinner before https://staging.app.weareminigolf.com/last-chance

- [ ] logo should have explicity width and height to reduce layout shifts and improve CLS
`<img src="/img/logo-principle.8dc3d543.png">`

**Comment by weareminigolf** [comment]
could we do one spinner for everything? like at the very begining one dedicated page saying : 
"We are initiating your game, depending on your connection this might take up to a minute" or something like that?

**Comment by paulchrisluke** [comment]
@weareminigolf possibly. I think re-uploading web optimized images will be the biggest difference here. It represents about 80% of our load time currently. We should start there and then address other ways to cover the load time if its still a problem

**Comment by weareminigolf** [comment]
Sure. I’ll talk to Marine so she updates everything on the drive

**Comment by weareminigolf** [comment]
Not sure she can do it today though

**Comment by weareminigolf** [comment]
Every asset is available with light weight on the drive
