### ISSUE TITLE
"Detailled scores" ajustments

### ISSUE THREAD

**Issue by weareminigolf** [whynotearth/we-are-mini-golf-frontend#131]
Can you remove the "review us" button at the top and make the two buttons review us/Start New game, visible at all time?

Thank you!

**Comment by paulchrisluke** [comment]
can we see this in a screenshot/design please?

**Comment by freedannyv** [comment]
I think I know what they're saying, I'll shoot a screenshot into messenger in a bit @paulchrisluke
