### ISSUE TITLE
use playerSelectBackground from api

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/we-are-mini-golf-frontend#147]

**Comment by freedannyv** [comment]
We can't do this until we have a course select screen. The api call comes later than this point at the moment.

**Comment by paulchrisluke** [comment]
we may have a method now @giteshk11 ?

**Comment by paulchrisluke** [comment]
@freedannyv the api is now ready, can connect with @giteshk11 about it

**Comment by paulchrisluke** [comment]
we can make a basic version of teh course selector

"Welcome please select your course"

plain background color

squares to allow them to select a course
