### ISSUE TITLE
New Course Generation

### ISSUE THREAD

**Issue by weareminigolf** [whynotearth/we-are-mini-golf-frontend#149]
I tried to create a new course "example course" on the back end, and published it. I changed only one square in the navigation path just to be able to differentiate them. It seems  
app.weareminigolf.com
app.weareminigolf.com/Angkor-Wat-Putt
app.weareminigolf.com/Example-course

are leading to the same course (the first one I created and shows in the url only the root domain (app.weareminigolf.com)), it doesn't seem to create new courses on the front end at the URL app.weareminigolf.com/+slug

**Comment by giteshk11** [comment]
this issue is fixed
