### ISSUE TITLE
Drawer/PopUp for current ranking 

### ISSUE THREAD

**Issue by weareminigolf** [whynotearth/we-are-mini-golf-frontend#178]
The current way we show the scores/ranking poses problems in real life conditions..
As we discussed the new design would be a pop up/drawer that shows the same table as shown in the final ranking page.
here is the design proposed by Marine

https://user-images.githubusercontent.com/76088063/108593896-d9106e80-7376-11eb-9c25-5cb5d513d3ca.mp4

**Comment by paulchrisluke** [comment]
this is a fairly large refactor, will take some time @giteshk11

**Comment by weareminigolf** [comment]
Any estimate of the time needed?

On 22 Feb 2021, at 10:31, Paul Chris Luke <notifications@github.com> wrote:

﻿

this is a fairly large refactor, will take some time @giteshk11<https://github.com/giteshk11>

**Comment by paulchrisluke** [comment]
@giteshk11 is finishing up the other two issues from designs, but has a full work week ahead for this. We may need to wait for @freedannyv to get back, or I can try and engage another developer?
