### ISSUE TITLE
Responsive Issue - Transition screen alignment 

### ISSUE THREAD

**Issue by weareminigolf** [whynotearth/we-are-mini-golf-frontend#186]
The transition screen is by default aligned on top of the screen, but on small screen we lose the PAR information.

Could you show it by default in the middle of the screen? 

Thanks!

![IMG_1370](https://user-images.githubusercontent.com/76088063/109293644-a7a80f00-785e-11eb-9bee-2569b5afef66.PNG)

**Comment by paulchrisluke** [comment]
@weareminigolf this should be resolved

**Comment by paulchrisluke** [comment]
@weareminigolf sorry wrong issue, I'll comment on the right one

**Comment by paulchrisluke** [comment]
@weareminigolf if you change the crop of these images to 100x100 does it look better for you? 
![image](https://user-images.githubusercontent.com/5694308/110193685-fa3d8880-7e67-11eb-9c5a-8cf94f923664.png)

looks like the images are too big

**Comment by weareminigolf** [comment]
Danny can correct me if I’m wrong but, I don’t think we can, the ratio is set so the background covers the lower half of the screen for the PAR information and the Upper part for the HOLE number. It was the only way to have it fit the background all the time unfortunately.
If I do it in a 100x100 square it will be aligned at the bottom of the screen and the numbers will be misplaced.




On 6 Mar 2021, at 10:38, Paul Chris Luke <notifications@github.com> wrote:

﻿

@weareminigolf<https://github.com/weareminigolf> if you change the crop of these images to 100x100 does it look better for you?
[image]<https://user-images.githubusercontent.com/5694308/110193685-fa3d8880-7e67-11eb-9c5a-8cf94f923664.png>

looks like the images are too big

**Comment by paulchrisluke** [comment]
@weareminigolf we resolved this issue by baking the numbers into the image itself, and using only the transition screen in the strapi backend to place it:

![image](https://user-images.githubusercontent.com/5694308/110198656-b148fc80-7e86-11eb-90ae-b1834a261a45.png)

the dimensions are 590x1280 . An example image is here:
![Frame 5-min](https://user-images.githubusercontent.com/5694308/110198677-caea4400-7e86-11eb-8868-f396cdbdb2d6.jpg)

the transition screens will need to resized with numbers baked into the image, and then uploaded to staging backend for the rest of the transition screens to work
