### ISSUE TITLE
Responsive Issue - Final Ranking Screen

### ISSUE THREAD

**Issue by weareminigolf** [whynotearth/we-are-mini-golf-frontend#191]
There is a responsiveness issue here, the "Detailed Scores" isn't high enough on my screen and doesn't read as it is on cleat background.

if too hard to set, can you put it on a white background and set the color to our dark green/bleu?

**Comment by weareminigolf** [comment]
![IMG_1377](https://user-images.githubusercontent.com/76088063/109296049-5437c000-7862-11eb-8421-7bf43e5ccbff.PNG)

**Comment by giteshk11** [comment]
We can fix this how we fixed the transition screen. For that, we need to extract assets.
But the easy solution would be this.
> if too hard to set, can you put it on a white background and set the color to our dark green/bleu?

@paulchrisluke @weareminigolf

**Comment by weareminigolf** [comment]
Not sure I understand. you would like another asset that would consist in a white frame with "Final Ranking" Written on it?

**Comment by weareminigolf** [comment]
https://res.cloudinary.com/doblhgoan/image/upload/v1614927984/we-are-mini-golf/Detailed_scores_dzjusn.png

**Comment by paulchrisluke** [comment]
@giteshk11 We probably just float a button in this case yeah? https://res.cloudinary.com/doblhgoan/image/upload/v1614927984/we-are-mini-golf/Detailed_scores_dzjusn.png

**Comment by paulchrisluke** [comment]
@freedannyv if you have time, this one is pretty simple. Create a button like this and float it above the content https://res.cloudinary.com/doblhgoan/image/upload/v1614927984/we-are-mini-golf/Detailed_scores_dzjusn.png

**Comment by giteshk11** [comment]
@freedannyv can work on this it's pretty easy.
