### ISSUE TITLE
[backlog]Close behavior on final score card

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/we-are-mini-golf-frontend#196]
- [ ] CLOSING ISSUE
The Drawer only closes when we click outside of the drawer.
it would be good to have more possibilities for a more intuitive UX
          - [ ] Close when we gesture  it down
          - [ ] Close when we click again on the footer
          
 

https://user-images.githubusercontent.com/76088063/109265582-5d606700-7839-11eb-87da-91aa60cb2a1f.mov

For swiping support, we can look at https://github.com/mlyknown/vue-gesture

**Comment by freedannyv** [comment]
@paulchrisluke  I fixed all of the nav buttons in my last PR

**Comment by paulchrisluke** [comment]
@freedannyv you mean clicking on the nav bar to close?

**Comment by freedannyv** [comment]
@paulchrisluke  yes exactly. But clicking outside and swipe no longer functional

**Comment by paulchrisluke** [comment]
I would revert to the functionality that was working (click outside to close) rather than implement a new feature which breaks existing ones. 

This issue is a new feature request, and can be backlogged as long as the existing funcionality of clicking outside to close is working
