### ISSUE TITLE
responsive issue, please hole number and par in handheld sign

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/we-are-mini-golf-frontend#34]
- [x] ensure numbers are placed properly in flags on transition screen

- [X] ![image](https://user-images.githubusercontent.com/5694308/103450100-054b2f80-4ce4-11eb-997c-bba6b3108a61.png)

- [ ] ![image](https://user-images.githubusercontent.com/5694308/103450116-214ed100-4ce4-11eb-95cd-f718c85325c2.png)

**Comment by freedannyv** [comment]
Last hole, total score issue fixed. The Hole No is challenging as the screen size changes, the board grows/shrinks and changes position

**Comment by paulchrisluke** [comment]
will tag @giteshk11 for hole number, we may want to tweak design too. Can discuss

**Comment by freedannyv** [comment]
aside from what I mentioned above, the other issue is addressed in #40

**Comment by paulchrisluke** [comment]
if this responsive issue is complex we can change the design, we are messaging in facebook about it tonight and tomorrow. Let me know
