### ISSUE TITLE
add finish screen

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/we-are-mini-golf-frontend#39]
![image](https://user-images.githubusercontent.com/5694308/103450252-02e9d500-4ce6-11eb-8988-ccd021f980c9.png)

screen 16

https://xd.adobe.com/view/f3af46d7-bbb6-4207-796b-8a96370ed2e5-859e/screen/77d6d12b-e86e-4064-9efe-2b01a2273eb0/?fbclid=IwAR1IaaIG7nx-t5BCsu7sIlYHJGs_CWCdTkHgkkDaYEwgLHOkVQAl2gsd5jk

**Comment by giteshk11** [comment]
@paulchrisluke @freedannyv if this issue is done we can close this.
