### ISSUE TITLE
add finish screen badge logic

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/we-are-mini-golf-frontend#42]
https://docs.google.com/spreadsheets/d/1QSjVDhdcDLQftyLLeDn0Qb59EWcVV14p_Wy3vGhyU7g/edit#gid=1910211792

![image](https://user-images.githubusercontent.com/5694308/103457291-8f20ea00-4d30-11eb-9764-80eed99222b0.png)

page 29 https://xd.adobe.com/view/f3af46d7-bbb6-4207-796b-8a96370ed2e5-859e/screen/bd1288b1-3670-43db-8257-bba2fc1ca748/

**Comment by freedannyv** [comment]
WIP. Logic completed, working on functionality - displaying the results
