### ISSUE TITLE
client revisions - detailed score issues

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/we-are-mini-golf-frontend#52]
Detailed scores | Only 12 holes show
-- | --
  | Hole 0 at the top?
  | PAR don't match the PAR information from the back office
  | Not sure the score are in the right order if the player decided to jump a hole and come back later?

**Comment by freedannyv** [comment]
Scores aren't in correct order. I messaged Kaze last night, it needs to be worked so in the creation of the game we make an array filled with null or 0 values that we can update with the holes' index position. Currently we just have `holeScore: [ ]` when created and we push the scores as the holes are completed.

I think it's backend stuff, I haven't seen the code for course creation, but I think that's the fix

**Comment by freedannyv** [comment]
This is completed in the last PR
