### ISSUE TITLE
add last hole warning

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/we-are-mini-golf-frontend#53]
![image](https://user-images.githubusercontent.com/5694308/104583819-30466380-5694-11eb-90bc-b73af6758fe0.png)

Image assets (background): 

https://drive.google.com/file/d/1-QyIRv2G_52xNlegARb1WzhfiaQXEtpi/view?usp=sharing

Description, should show unfinished holes if the player attempts to start the last hole. "Tackle" sends them back to course map

**Comment by freedannyv** [comment]
Can we get a design for this?

**Comment by paulchrisluke** [comment]
@freedannyv designs updated above

**Comment by paulchrisluke** [comment]
@freedannyv this should appear when you click on the last hole BEFORE you play. It's odd to click go to awards ceremony and then be warned. You should be warned before you play last hole
