### ISSUE TITLE
change conditional phrases to pop-up for responsive readiness

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/we-are-mini-golf-frontend#63]
2. About the conditional sentences on screen 7-Current hole recap, we've made some design changes to make them stand out more and help with their readability no matter the screen size. 
We've removed them from the screen and instead placed them in a pop-up box that will appear automatically after a one-second delay. To remove it from the screen after reading it, instead of a "X" to close it, we would like for a simple swipe or click from the user to make it move all the way to the top of the screen, like a drawer transition, leaving just the bottom border of the box visible. This way, if the user wants to read it again, he can pull it back (or click on it to make it show up again).

https://user-images.githubusercontent.com/5694308/104584948-ee1e2180-5695-11eb-801d-7c5d6c1cde90.mp4

https://xd.adobe.com/view/f3af46d7-bbb6-4207-796b-8a96370ed2e5-859e/screen/1ed0f7d1-bcbf-4675-9059-ebb963ad77df/specs/?fbclid=IwAR2JtcPVNo3jGrcAVF6GSar2FRFYT1rVzWBn5P8JvwZRVgzTK46aoS6GTks

**Comment by freedannyv** [comment]
This is done. I just need to refactor it for animation purposes. I may call on @giteshk11 to help guide me
