### ISSUE TITLE
[bug] player name input field does not show on initial load

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/we-are-mini-golf-frontend#84]
https://staging.app.weareminigolf.com/player-names

this input modal doesn't show on initial load

![image](https://user-images.githubusercontent.com/5694308/105038229-a3374c00-5a91-11eb-9846-d503518250ad.png)

**Comment by freedannyv** [comment]
I fixed it once using params but was informed that it wasn't best practice. I will pass to Kaze because the code looks fine to me, I don't know why it doesn't work.

**Comment by weareminigolf** [comment]
There might also be a design issue on both Safari and Chrome on Iphones.

The name box and drop down menus are not really clean.
![140055767_411315423291932_4798321626582074236_n](https://user-images.githubusercontent.com/76088063/105131543-6f881080-5ae9-11eb-99c5-844f424a740d.jpg)
![Uploading 139901007_405884920474171_421555776224413708_n.jpg…]()

**Comment by giteshk11** [comment]
@weareminigolf we will have a separate issue for that because it's an iOS-related issue.
Closing this issue for now.
