### ISSUE TITLE
[bug] two arms show on final score transition

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/we-are-mini-golf-frontend#91]
![image](https://user-images.githubusercontent.com/5694308/105058183-85c1ac80-5aa8-11eb-9758-398dac438d89.png)

**Comment by freedannyv** [comment]
I believe that @giteshk11 is working on this

**Comment by paulchrisluke** [comment]
he isn't, this one is yours @freedannyv , I think you made this screen originally?

**Comment by freedannyv** [comment]
Fixed in PR
