### ISSUE TITLE
[backlog] scroll down navigation path when open

### ISSUE THREAD

**Issue by weareminigolf** [whynotearth/we-are-mini-golf-frontend#96]
I see when we finish a hole and get back to the path, it first opens on the top and then goes to the bottom. We mentioned doing it with a slow scrolling down on that page.

**Comment by paulchrisluke** [comment]
it should probably scroll to last hole played, but we need to add some logic for back button behavior in general. I'm placing this animation in backlog until navigation/back/forward/routing is finalized

**Comment by weareminigolf** [comment]
it is scrolling down on Android but not on IOS, also, can you make it scroll down a bit slower?

Thanks!
