### ISSUE TITLE
add back button support

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/we-are-mini-golf-frontend#97]
@click="$router.go(-1)"

If I hit back at certain points, it doesn't recognize what hole I was on:

![image](https://user-images.githubusercontent.com/5694308/105178465-a5b1a880-5b5a-11eb-89df-d0a687638e6e.png)

another example is pressing back from the review screen after you tap the social share (that social share should probably open in a new tab btw)

back button from score input should not go to transition screen, but back to map. If the score has not been entered, the hole should not be marked as active https://staging.app.weareminigolf.com/game-scores

**Comment by giteshk11** [comment]
what is this?

**Comment by paulchrisluke** [comment]
This is from joe, our back swipe support behaves weird (try to swipe back from enter score screen)
